Assignment: Adding Introductory txt file to DemoWebsit.
SaumyaSingh1/DemoWebsite pull request #86
Opened 2021-03-20 18:09 UTC by Diksha-11

Hello @SaumyaSingh1 , I have completed the assignment that you gave us in the GSSOC'21 session "Getting started with Open Source"

2021-03-23 01:23 UTC, SaumyaSingh1 commented on MyIntro.txt
> +Hi, I am Diksha Sharma.
Please put this file inside the [Assignments Folder](https://github.com/SaumyaSingh1/DemoWebsite/tree/master/Assignments) :)
Then we will be good to merge this PR

2021-03-23 01:24 UTC, SaumyaSingh1 requested changes

2021-03-23 01:24 UTC, SaumyaSingh1 commented on MyIntro.txt
> +I'm a 2nd year B.Tech student, Persuing my in B.Tech Information Technology from ITM Group of Institutions , Gwaloir, M.P.
Hi @Diksha-11 

Please put this file inside the [Assignments Folder](https://github.com/SaumyaSingh1/DemoWebsite/tree/master/Assignments) :)
Then we will be good to merge this PR

2021-04-11 09:50 UTC, Diksha-11 commented on MyIntro.txt
> +I'm a 2nd year B.Tech student, Persuing my in B.Tech Information Technology from ITM Group of Institutions , Gwaloir, M.P.
Sure @SaumyaSingh1

2021-04-11 10:12 UTC, closed without merging